next:
      image: node:10
      mounts:
      - ".:/src"
      commands:
      - ["next", "-j$1"]
      envs:
      - AUTH_SECRET=`$AUTH_SECRET`

next-custom:
      image: node:10
      mounts:
      - ".:/src"
      commands:
      - ["npm", "-j$1"]
      envs:
      - AUTH_SECRET=`$AUTH_SECRET`

build:
      image: node:10
      mounts:
      - ".:/src"
      commands:
      - ["next", "build"]
      envs:
      - AUTH_SECRET=`$AUTH_SECRET`

deploy-heroku:
      - follow: build
      mounts:
        - "./build:/src"
      commands:
        - ["curl", "https://cli-assets.heroku.com/install.sh", "|", "sh"]
        - ["git", "add", "./src"]
        - ["heroku", "git:remote", "-a", "-j$1"]

lint:
      image: node:10
      mounts:
      - ".:/src"
      commands:
      - ["npm", "run", "lint"]
      envs:
      - AUTH_SECRET=`$AUTH_SECRET`

init:
    - name: nextjsspa
      image: node:10
      mounts:
      - ".:/src"
      commands:
      - ["npm", "install"]
      envs:
      - AUTH_SECRET=`$AUTH_SECRET`