build:
  - image: golang
    commands:
    - ["go", "build", "-o", "<project_name>"]
    envs:
    - XDG_CACHE_HOME=/tmp/.cache 

lint:
  - image: golangci/golangci-lint
    commands:
    - ["golangci-lint", "run"]
    envs:
    - XDG_CACHE_HOME=/tmp/.cache 

vet: 
  - image: golang
    commands:
    - ["go", "vet", "./..."]
    envs:
    - XDG_CACHE_HOME=/tmp/.cache 

fmt: 
  - image: golang
    commands:
    - ["go", "fmt", "./..."]
    envs:
    - XDG_CACHE_HOME=/tmp/.cache 

test:
  - image: golang
    commands:
    - ["go", "test", "./..."]
    envs:
    - XDG_CACHE_HOME=/tmp/.cache 
